services:
  - type: web
    name: ems-backend
    runtime: docker
    dockerContext: server
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
